### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ersimont** [healthiers/mini-dash#5] opened 2017-07-22 13:34 UTC
Great library! I have been writing my own little utilities with objectives similar to what you laid out for this project. And the resulting code is very similar! (Except that yours is more complete, well tested, open source, and probably better in many other ways. 😄)

May I use it? I cannot find a license file, which means [I may not](https://choosealicense.com/no-license/) (without special permission).

**Comment by ersimont** [comment] 2017-07-22 14:09
Fun story about how I found this library:
I was starting to set up a repository to open-source the code I've written. I was about to commit it using the name `mini-dash` when I thought, "I should see if that name is available in the npm registry first." 😄 I was amazed and excited to see that you already did almost exactly what I wanted to do!

**Comment by bali182** [comment] 2017-07-22 20:54
Hey @ersimont!

I'm really glad you found it useful & thanks for the compliments! You are absolute welcome to use it!
I will add the most permissive license I can find (I guess it is MIT?)

Yes, regarding the goals, I was not very satisfied that with lodash/underscore etc, I have to pay attention to which method mutates it's inputs and which do not. Also I wasn't satisfied with the extreme bundle size that they introduced... I guess you are in the same shoes 😄

**Comment by bali182** [comment] 2017-07-22 20:58
Closed by 37976780d073a288ab30d1e1961961ed729f023d

**Closed by bali182** 2017-07-22 20:58 UTC

**Comment by ersimont** [comment] 2017-07-22 21:21
Great, thank you! I will definitely be using this!

I've been working on getting all the (similar) code I wrote into a repository. You can see it in progress here: https://github.com/simontonsoftware/micro-dash. We should discuss if/how to combine our efforts best. It looks like the two of us have implemented surprisingly different sub-sets of `lodash`, so I have many functions implemented that you do not and vice-versa.  And for the ones that we both implemented, you have tests!!

Some differences in our objectives, to help us think about how best to share our efforts:
- I am specifically reimplementing `lodash` functions, using their naming & function signatures. My goal is to be api-compatible, though sometimes without some of the optional parameters. I have not looked at `undecscore`.
- One or two of the functions I implemented so far do mutate arguments. It is more important to me to copy `lodash`'s behavior. However, I have not wanted very many functions that do mutation, so I have not implemented many 😄.  The only ones I can think of are `pull` and `remove`.
- I have not given any thought to avoiding `Array.filter`, `Array.map`, etc. I'm curious: why is this one of your objectives?

- I am using typescript.
- I lean on ES2015 features often (like arrow functions and the spread operator). This makes for a slightly smaller bundle for those using ES2015 directly, but slightly larger for those using ES5.

**Comment by bali182** [comment] 2017-07-22 22:10
Yep I think we had slightly different goals in mind. Mine was just having standard functional utilities without doubling the bundle size. Like "I need a `flatMap`? great I pull this lib in which only adds like [25 ](https://github.com/healthiers/mini-dash/blob/master/flatMap/index.js) lines of code instead of [2000](https://github.com/lodash/lodash/blob/4.5.0-npm-packages/lodash.flatmap/index.js)". But here is a rundown on why I did what:

- I wanted all functions to be as simple as possible (like how you would naively add it to your project after not finding a native solution). The reason for this, is that if You want to understand how a lodash function works, you have to spend quite some time sifting through the years of accumulated code in there. If you want to understand one of these methods? just look at the code and you get it in 1 minute.
- I wanted them NOT to take a combination of arguments (I think this is your goal as well, keep the API clean, and the arguments self explanatory without many variations). The reason for this is that lodash methods while working great, often take the weirdest combination of arguments without a problem, and return phony `undefined` or `null` results when simply the args are not as expected. What I wanted here, is if you have a problem with the arguments, you check the method (or the docs), or stop the debugger, and immediately see what is expected by the method and why is it failing or returning something different from what you expected.
- Avoid a build process. This is something that one can argue with since browsers can't really use this without at least "browserify"ing, but other than that I don't use any non ES5 features. This makes it fairly easy to use this lib, regardless of how your final project will end up. Using a complex build process? No probs, just import this stuff. Using node? Just require what you need and it should work. You get the point.
- Immutabilty - this is just my prefered coding style, I never mutate what I get as argument, especially if this method is exported. In my opinion it just makes your easier to reason about. Now while I can see some utility for the mentioned 2 methods (`pull` and `remove`) in both cases I would just go with `Array#filter` and work with the filtered results. But in lodash there are more of the mutating methods, let me give you a few: `fill`, `pull*`, `remove`, `reverse`, `merge*`, `assign`... And some of these would have great utility for me - if they were not mutating the input.
- I saw that `map`, `filter` and `reduce` give incosistent performance results in different browsers, and this is why lodash & underscode authors justify their duplicated existence, but I belive, that if there's native support for it, I shouldn't reinvent the wheel, that's why I haven't added them.

Anyways, the somewhat feature compatible lodash copy with reduced argument variety sounds interesting. I checked out `micro-dash` (someone with slightly different goals will come up with `nano-dash`, I can feel it 😄), and if you want to go ahead with the typescript version, I'm willing to help with that. I think you are on the right path with the rollup build, that seems to be the best option to do this kind of thing. Only thing I would do if I was you, is add an option for the consumer of the lib to only import what they need (not really sure how this works in ts, it's been a long time I looked at it). 

However if you are ok with how this lib works, we can add the definitions here too as mentioned in #7

**Comment by ersimont** [comment] 2017-07-23 02:07
> Mine was just having standard functional utilities without doubling the bundle size.

That was exactly my initial motivation, too. I forget which lodash function I used first, but it pulled in a ton of code to my final bundle worrying about non-ascii characters, or some such thing.

> You want to understand how a lodash function works, you have to spend quite some time sifting through the years of accumulated code in there. If you want to understand one of these methods? just look at the code and you get it in 1 minute.

That makes a lot of sense. I've had the same experience trying to understand lodash code.

> Now while I can see some utility for the mentioned 2 methods (pull and remove) in both cases I would just go with Array#filter and work with the filtered results.

I'm slowly embracing immutability more. Probably after some time I won't have any use for `pull` and `remove` anymore, either.  😄 

>  I belive, that if there's native support for it, I shouldn't reinvent the wheel, that's why I haven't added them.

I agree. Your readme says "All methods use for loops under the hood (no `Array.filter`, `Array.map`, etc)". That makes me think you have a design decision not just to avoid re-implementing them, but to avoid using them in your internal implementation of the other functions.  I was curious why that would be.

> someone with slightly different goals will come up with nano-dash, I can feel it 

I bet you're right! 😄

> However if you are ok with how this lib works, we can add the definitions here too as mentioned in #7

I'll comment more on this over there.

**Comment by bali182** [comment] 2017-07-24 09:13
I'm going to reply to the question related to for loops. The reason behind that is, that most of these methods would be some sort of composite of the functional utilities already present on `Array`. 

For example `clone` which clones an object, and looks like this currently:
https://github.com/healthiers/mini-dash/blob/master/clone/index.js

Would looks something like this:

```js
export const clone = object => Object.keys(object).reduce((result, key) => {
  result[key] = object[key]
  return result
}, {})
```

Which is 2 iterations (`2n` where `n = Object.keys(object).length`), since first we have to fetch the keys, which is `n` (+ a new array in memory) then we have to iterate on that with `reduce` again, and build the final object.

So my motivation behind this was purely based on trying to make it as performant as possible, without trying to micro-optimize it.

Similarly if you look at let's say `flatMap` which currently looks like this:
https://github.com/healthiers/mini-dash/blob/master/flatMap/index.js

Would be something like this:

```js
export const flatMap = (input, transform) => [].concat(...input.map(transform))
```

Which looks arguably horrible again performance wise: first we a do `map` which is a n iterations + a new array then we concat them in a separate step, which looks in itself should be close to the current `flatMap` methods performance.

As for the rest where this wouldn't be the case, I just didn't want to use separate coding style.

**Comment by ersimont** [comment] 2017-07-24 22:32
I see.  Thanks for the explanation!  Out of curiosity, have you checked how much performance difference it makes?

**Comment by bali182** [comment] 2017-07-25 09:35
I started working on a lib that allows you to write proper benchmarks (partly because I wanted to actually test this stuff) but haven't really finished it yet. I probably will do it but not really sure when.

**Comment by bali182** [comment] 2017-07-25 15:25
If you want to check it out it's here https://github.com/bali182/cathedra . It's far from complete, but I think has a nice api and a CLI unlike the existing benchmark package

**Comment by bali182** [comment] 2017-07-26 08:45
@ersimont also if you plan to be feature complete with lodash, I encourage you to check out the older brother, underscore. The methods there are actually (much) easier to understand, and since lodash was designed to be kind of a drop in replacement for underscore, it should be a good place to start "appropriating" stuff :D

https://github.com/jashkenas/underscore/blob/master/underscore.js

**Comment by ersimont** [comment] 2017-07-26 09:47
I am familiar with underscore, but not its source. I'll have to check it out, along with the payload size(s) it produces. (I made a tool to test that. It looks like there are a number of the lodash functions that suck in 14K of support code!) Good idea!

I don't have any need to be feature complete with lodash, but if underscore keeps payload sizes down I might not even need what I already have!

**Comment by ersimont** [comment] 2017-07-26 10:38
Hey look, I found another one too: https://amp.ampersandjs.com

**Comment by bali182** [comment] 2017-07-26 12:57
Def a good reference point for implementations, but posting a 70 npm packages? 😮 It just seems wasteful to me. Also lots of garbage in your package.json when you install these modules individually. 

Also I did some benchmarking with a few methods. With small inputs mini-dash wins every time, since it does no input validation, but underscore/lodash "wastes" a lot's of time doing null checks, etc. With big inputs there was not much difference. In the weekend I will probably have some time and post proper benchmarks!

**Comment by ersimont** [comment] 2017-07-26 22:57
I don't have much concern about performance in my applications (so far?), but it's always fun to have numbers! Feel free to benchmark mine, too. 😉
